### ISSUE TITLE
readme artifact links return 403

### ISSUE THREAD

**Issue by awill1988** [TimoSto/ThesorTeX#193] opened 2023-06-25 23:37 UTC
Hello,

I was trying to grab a binary as described in [downloads](https://github.com/TimoSto/ThesorTeX#downloads) and letting you know those resources are currently non-public.

Used this link:
https://thesortex-artifacts.s3.eu-central-1.amazonaws.com/thesisTool/latest/mac_silicon/ThesorTeX.zip

![Screenshot 2023-06-25 at 5 30 53 PM](https://github.com/TimoSto/ThesorTeX/assets/12990461/54a12762-3e35-49e6-af38-257b0fa0e539)

**Comment by TimoSto** [comment] 2023-06-26 14:30
Hi there,

this issue occurred because the link was incorrect. It should be [https://thesortex-artifacts.s3.eu-central-1.amazonaws.com/thesisTool/latest/mac_arm/ThesorTeX.zip](https://thesortex-artifacts.s3.eu-central-1.amazonaws.com/thesisTool/latest/mac_arm/ThesorTeX.zip). I just fixed it in the readme.

Thanks for the notice! If the problem is now resolved, feel free to close this issue.

**Closed** 2023-06-28 01:09 UTC
